set-option -g mouse on
set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Smart scrolling: Pass events to apps like vim/less, otherwise enter copy mode
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
